[package]
name = "m_lexer"
version = "0.0.4"

authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/m_lexer"
license = "MIT OR Apache-2.0"

description = """
A simple extensible regular expressions based lexer
"""

[dependencies]
regex = "1"
